date command requires RTC
  LD      spl/drivers/built-in.o
cmd/built-in.o: In function `do_date':
/mnt/u-boot/cmd/date.c:65: undefined reference to `rtc_reset'
/mnt/u-boot/cmd/date.c:66: undefined reference to `rtc_set'
/mnt/u-boot/cmd/date.c:75: undefined reference to `rtc_get'
/mnt/u-boot/cmd/date.c:87: undefined reference to `rtc_set'
/mnt/u-boot/cmd/date.c:102: undefined reference to `rtc_get'
cmd/built-in.o: In function `do_usb_mass_storage':
/mnt/u-boot/cmd/usb_mass_storage.c:170: undefined reference to `fsg_init'
/mnt/u-boot/cmd/usb_mass_storage.c:217: undefined reference to `fsg_main_thread'
arm-linux-gnueabihf-ld.bfd: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf32-arm.c:7696
arm-linux-gnueabihf-ld.bfd: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf32-arm.c:7696
arm-linux-gnueabihf-ld.bfd: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf32-arm.c:7696
arm-linux-gnueabihf-ld.bfd: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf32-arm.c:7696
arm-linux-gnueabihf-ld.bfd: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf32-arm.c:7696
arm-linux-gnueabihf-ld.bfd: error: required section '.rel.plt' not found in the linker script
arm-linux-gnueabihf-ld.bfd: final link failed: Invalid operation
  LD      spl/u-boot-spl